### ISSUE TITLE
Inconsistencies with continuous features

### ISSUE THREAD

**Issue by akaigraham** [learn-co-curriculum/dsc-interaction-terms-lab#2]
after preprocessing data, ames_cont is concatenated to ames_ohe instead of ames_log_norm, resulting in preprocessing of continuous variables not flowing into the regression.  This produces an understated R2 value and results in different interactions resulting in the highest r2.  Additionally, at the end of the lab, when predicting values based on LotArea, the log transformed values are used - - inconsistencies make this lab very confusing when looking at the solution.  

Additionally, when getting dummy variables, drop_first is not set as described in previous lessons.

**Comment by hoffm386** [comment]
Hi @akaigraham we have a revamped version of this lab available here: https://github.com/learn-co-curriculum/dsc-interaction-terms-lab-v2-5
